[[locations]]
lat = 53.4574056
lon = 7.5346991
name = "Wasserwerk Aurich"

[[locations]]
lat = 53.7280147
lon = 7.3846392
name = "Wasserwerk Baltrum"

[[locations]]
lat = 52.9105001
lon = 8.237373
name = "Wasserwerk Großenkneten"

[[locations]]
lat = 53.6005134
lon = 7.5953426
name = "Wasserwerk Harlingerland"

[[locations]]
lat = 52.8969274
lon = 8.6158132
name = "Wasserwerk Harpstedt"

[[locations]]
lat = 52.5659253
lon = 8.103196
name = "Wasserwerk Holdorf"

[[locations]]
lat = 53.75096
lon = 7.5031164
name = "Wasserwerk Langeoog"

[[locations]]
lat = 53.496342
lon = 7.2999953
name = "Wasserwerk Marienhafe"

[[locations]]
lat = 53.2720647
lon = 8.1360754
name = "Wasserwerk Nethen"

[[locations]]
lat = 53.522369
lon = 7.8332808
name = "Wasserwerk Sandelermöns"

[[locations]]
lat = 53.7739455
lon = 7.6907031
name = "Wasserwerk Spiekeroog"

[[locations]]
lat = 52.9211309
lon = 7.8883566
name = "Wasserwerk Thülsfelde"

[[locations]]
lat = 53.791442
lon = 7.9067271
name = "Wasserwerk Wangerooge"

[[locations]]
lat = 53.2668251
lon = 7.935013
name = "Wasserwerk Westerstede"

[[locations]]
lat = 52.8794732
lon = 8.4479051
name = "Wasserwerk Wildeshausen"

[[locations]]
lat = 52.721792
lon = 8.286841
name = "Kay SWAT"
